# Generated by Django 2.2.2 on 2020-04-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(default=1, verbose_name=' team_id')),
                ('team_name', models.CharField(default=1, max_length=29, verbose_name='team_name')),
            ],
        ),
        migrations.CreateModel(
            name='playe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=1, verbose_name=' player_id')),
                ('player_name', models.CharField(default=1, max_length=29, verbose_name='player_name')),
                ('no_of_matches', models.IntegerField(default=1, verbose_name='no_of_matches')),
                ('total_score', models.IntegerField(default=1, verbose_name='Total Score')),
                ('teams', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.tea')),
            ],
        ),
    ]
