# Generated by Django 2.2.2 on 2020-04-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0002_remove_playe_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='playe',
            name='teams',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.tea'),
        ),
    ]
