# Generated by Django 2.2.2 on 2020-04-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0005_auto_20200411_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playe',
            name='team_name',
            field=models.CharField(max_length=78, verbose_name='team_name'),
        ),
    ]
