# Generated by Django 2.2.2 on 2020-04-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0006_auto_20200411_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playe',
            name='team_name',
            field=models.CharField(default=1, max_length=256, verbose_name='team_name'),
        ),
    ]
