# Generated by Django 2.2.2 on 2020-04-11 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0007_auto_20200411_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tea',
            options={},
        ),
        migrations.RemoveField(
            model_name='tea',
            name='team_id',
        ),
        migrations.AlterField(
            model_name='playe',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.tea'),
        ),
    ]
