# Generated by Django 2.2.2 on 2020-04-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0008_auto_20200411_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playe',
            name='team_name',
        ),
    ]
