# Generated by Django 2.2.2 on 2020-04-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0009_remove_playe_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playe',
            name='team_name',
            field=models.CharField(default=1, max_length=256, verbose_name='team_name'),
        ),
        migrations.AddField(
            model_name='tea',
            name='team_id',
            field=models.IntegerField(default=1, verbose_name=' team_id'),
        ),
    ]
