# Generated by Django 2.2.2 on 2020-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0010_auto_20200411_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default=1, max_length=256, verbose_name='team_name')),
                ('player_id', models.IntegerField(default=1, verbose_name=' player_id')),
                ('player_name', models.CharField(default=1, max_length=29, verbose_name='player_name')),
                ('no_of_matches', models.IntegerField(default=1, verbose_name='no_of_matches')),
                ('total_score', models.IntegerField(default=1, verbose_name='Total Score')),
            ],
        ),
    ]
