# Generated by Django 2.2.2 on 2020-05-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0011_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='playe',
            name='total_wicket',
            field=models.IntegerField(default=1, verbose_name='Total wicket'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_wicket',
            field=models.IntegerField(default=1, verbose_name='Total wicket'),
        ),
    ]
